apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-bdd
    test: {{ .Values.database.name }}-bdd
  name: {{ .Release.Name }}-bdd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bdd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-bdd
    spec:
      containers:
      - image: nicodeur/k8s-bdd:latest
        imagePullPolicy: Always
        name: k8s-bdd
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-secret
                key: password
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: tuto-storage
            subPath: mysql-tuto
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: tuto-storage
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}-bdd
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
