apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.exposeUrl }}
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: {{ .Release.Name }}-api
              servicePort: 3000
