apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tuto-api
  name: tuto-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tuto-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tuto-api
    spec:
      containers:
      - image: nicodeur/k8s-api:latest
        imagePullPolicy: Always
        name: k8s-api
        env:
        - name: MYSQL_HOST
          value: tuto-bdd
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tuto-secret
              key: password
        - name: MYSQL_DATABASE
          value: workshop
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
